apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: discounts
    {{- include "ecommerce.labels" . | nindent 4 }}
  name: discounts
spec:
  replicas: {{ .Values.discounts.replicas }}
  selector:
    matchLabels:
      service: discounts
      app: ecommerce
  strategy: {}
  template:
    metadata:
      labels:
        service: discounts
        {{- include "ecommerce.labels" . | nindent 4 }}
    spec:
      containers:
      - image: {{ .Values.discounts.container.image }}
        imagePullPolicy: {{ .Values.discounts.container.pullPolicy }}
        name: {{ .Values.discounts.container.name }} 
        command: ["ddtrace-run"]
        args: ["flask", "run", "--port=5001", "--host=0.0.0.0"]
        env:
          - name: FLASK_APP
            value: "discounts.py"
          - name: FLASK_DEBUG
            value: "1"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: pw
                name: db-password
          - name: POSTGRES_USER
            value: "user"
          - name: DATADOG_SERVICE_NAME
            value: "discountsservice"
          - name: DD_AGENT_HOST 
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_ANALYTICS_ENABLED
            value: "true"
        ports:
        - containerPort: 5001
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: discounts
    {{- include "ecommerce.labels" . | nindent 4 }}
  name: discounts
spec:
  replicas: {{ .Values.discounts.replicas }}
  ports:
  - port: {{ .Values.discounts.service.port }}
    protocol: TCP
  selector:
    service: discounts
    app: ecommerce